version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # If you need environment variables, uncomment and add them
    # environment:
    #   - NODE_ENV=production 